### PR TITLE
Refactored python script

### PR DESCRIPTION
**Pull request by conqp**
I took the liberty to completely refactor the python script `native.py`.  
I tested it with the dev-version of firefox.  

### Changes

- Broke down code into several separate functions (*divide and conquer*).
- Made use of some useful python structures like `namedtuple` and `Enum`.
- Made variable naming and indentation PEP8 compliant.

If you have any questions, please contact me.

### CODE REVIEW

**Comment by conqp** [comment]
https://github.com/GKFX/hide-ff-title-bar/pull/13/commits/1bc6781d06f86e3b5a771778e6c5bf3dc44d047e addresses https://github.com/GKFX/hide-ff-title-bar/issues/5

**Comment by GKFX** [comment]
@conqp Thank you very much for all this! I'm sorry I haven't been able to review it sooner but as soon as I'm available I'll try to get it merged if you're still happy with it.

**Comment by conqp** [comment]
@GKFX Yes sure. I'm sorry that I misinterpreted the long silence here for a lack of interest.

**Comment by dariuskl** [comment]
@conqp 
I was looking into a way of decorating new windows and just saw your work here. Just a hint: maybe it would be a more resource-conscious approach to add a listener for the [window creation event](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/onCreated) in the extension itself and send a native message from there instead of having the script running in the background.

**Comment by conqp** [comment]
@dariuskl I am not too well versed with Firefox plugin development. If you have a better solution for decorating new windows (and probably any other solution is better than my hack), I think it'd be great if you contributed your ideas in form of code. :)

**Comment by GKFX** [comment]
@conqp One of the major issues with this PR is that it removes the titlebar from all windows owned by Firefox, not just the "real" browser windows that display a webpage. It's possible that @dariuskl's approach is the correct solution here, since the window created events seem to fire only for proper windows.

**Comment by conqp** [comment]
@GKFX Well, the original script just decorated the *first* of the windows of the firefox process.  
I don't think that decorating all of the firefox process's windows on startup in itself is a problem, since there should be just one such window (I need to verify this).
I agree however, that this is a problem on the continuous decoration, which is also, why I disabled it as per default.
I completely agree, that @dariuskl's approach sounds way better (which I already stated).  
If you feel uncomfortable with this testing code in my PR, I can remove it.

**Comment by GKFX** [comment]
I'm very happy to work with what you've done; my original script was quite limited and did only decorate one window. I was just suggesting that the window created events might be the solution to identifying which windows are appropriate to decorate. Although since there doesn't appear to be  a straightforward link between the Window objects seen by the extension and the windows seen by the Python script (the IDs and even the initially reported titles are different) I'm considering just identifying browser windows on the basis that they contain a suitable string (such as "Firefox" or "Nightly") and are owned by the correct process.

**Comment by conqp** [comment]
I also see the problem with identifying the *main* windows of firefox.  
I will have a closer look at it when I find the time.
PS: With *I can remove it* I was referring to the testing code, not the entire PR request. ;)

**Comment by dariuskl** [comment]
> I think it'd be great if you contributed your ideas in form of code. :)

Fair enough. :-) I opened pull request #19, which includes the listener. New windows are correctly (un-)decorated. However, still all windows are affected.

Regarding that issue, I don't think there is a nice way of linking the Firefox windows to window manager IDs. Maybe it would be a solution to temporarily insert "markers" into the title with which browser windows can be differentiated? I'm not so sure yet whether this is a good idea, though.

**Pull request merged**
